### ISSUE TITLE
I cant get to the end

### ISSUE THREAD

**Issue by Rustymonkey238** [UnRealPacks/YouMadCraft-1.7#3]
so i am kind of upset because whenever i go to the end i crash and lose the world

the first time i was trying to get the stable division sigil  i went to the end and got a black screen then 
crashed i logged back on and crashed again

the second time i killed the ender dragon with an orespawn egg then the portal spawned and i accidentally fell in (it spawned underneath where i was standing) and have now lost that world 

and i was doing "good" in both the first one just got iron man armor and a chainsaw and the second one superman armor a chainsaw and all the project e armor and tools (red matter)

**Comment by UnRealDinnerbone** [comment]
Crash Report Please

**Comment by Rustymonkey238** [comment]
alright so i found out that i cant get to the end due to lack of memory so my bad and love the mod pack

**Comment by Rustymonkey238** [comment]
so it turns out that chocolate quest is the reason you cant go to the end it tries to create a structure as you enter the end and it crashes so if you remove chocolate quest and go to the end then you can enter without crashing

**Comment by UnRealDinnerbone** [comment]
Ok i updated the modpack can you tell me if the bug is still there please

**Comment by UnRealDinnerbone** [comment]
Fixed It I Think
